export interface Quote {
  id: number;
  businessName: string;
  company: string | null;
  contactName: string | null;
  email: string | null;
  phone: string | null;
  value: number;
  date: string;
  time: string;
  source: "Email" | "SMS" | "Website";
  status: "Won" | "Quote" | "Lost" | "Pending" | "Pre sales" | "Number Missing";
  trigger: string | null;
  /** Dropbox share link (File column in sheet) */
  file: string | null;
  /** Dropbox file path (Dropbox File Path column) */
  dropboxFilePath: string | null;
  /** Google Sheet row number (1-based); used for updates when synced */
  rowNumber?: number;
}

export const MOCK_QUOTES: Quote[] = [
  {
    id: 2,
    businessName: "Zimraan Business",
    company: "All In IT Solutions",
    contactName: "Zimraan Anjum",
    email: "zimraan@allinit.com.au",
    phone: "0414 933 249 58",
    value: 45000,
    date: "23-09-2025",
    time: "10:32 AM",
    source: "Email",
    status: "Won",
    trigger: "SMS Link Sent",
    file: "https://www.dropbox.com/scl/fi/q67xo",
    dropboxFilePath: "/aiit - ai dev projects/prop",
  },
  {
    id: 3,
    businessName: "Kevin Watters",
    company: "Motts.com.au",
    contactName: "Jason Khouri",
    email: "jason.khouri@motts.com.au",
    phone: null,
    value: 22750,
    date: "25-09-2025",
    time: "3:43 PM",
    source: "Email",
    status: "Won",
    trigger: "Number Missing",
    file: "https://www.dropbox.com/scl/fi/n5uo9",
    dropboxFilePath: "/aiit - ai dev projects/prop",
  },
  {
    id: 4,
    businessName: "Sonic E Bike",
    company: null,
    contactName: null,
    email: "ysfermiss@gmail.com",
    phone: null,
    value: 8500,
    date: "26-09-2025",
    time: "12:04 PM",
    source: "Email",
    status: "Quote",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 5,
    businessName: "Minto Masjid",
    company: null,
    contactName: "Tamrez Khan",
    email: "tamrez.khan@gmail.com",
    phone: null,
    value: 32000,
    date: "30-09-2025",
    time: "12:56 PM",
    source: "Email",
    status: "Pending",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 6,
    businessName: "Aviation Detailing Solutions",
    company: null,
    contactName: null,
    email: "ahmad.ghazal5@hotmail.com",
    phone: null,
    value: 15000,
    date: "18-10-2025",
    time: "2:22 PM",
    source: "Email",
    status: "Won",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 7,
    businessName: "Alps Group",
    company: null,
    contactName: null,
    email: "alpsgrouptyltd@gmail.com",
    phone: null,
    value: 18900,
    date: "22-10-2025",
    time: "9:08 AM",
    source: "Email",
    status: "Quote",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 8,
    businessName: "Divorced Online",
    company: "Lead Mouna Ref Website",
    contactName: null,
    email: "mouna.youssef2244@gmail.com",
    phone: null,
    value: 9200,
    date: "22-10-2025",
    time: "2:21 PM",
    source: "Email",
    status: "Quote",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 9,
    businessName: "Allied Health Clinic",
    company: null,
    contactName: null,
    email: "info@activefootcare.com.au",
    phone: null,
    value: 12400,
    date: "23-10-2025",
    time: "2:41 PM",
    source: "Email",
    status: "Quote",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 10,
    businessName: "Grace Care NDIS",
    company: null,
    contactName: null,
    email: "j.sharonroyal@gmail.com",
    phone: null,
    value: 27500,
    date: "23-10-2025",
    time: "3:40 PM",
    source: "Email",
    status: "Quote",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 11,
    businessName: "TSTPS Geofence Feature",
    company: "Reception Desk - TSTPS",
    contactName: null,
    email: "reception@tstps.com.au",
    phone: null,
    value: 42000,
    date: "27-10-2025",
    time: "10:32 AM",
    source: "Email",
    status: "Lost",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 12,
    businessName: "IQRA Academy",
    company: null,
    contactName: null,
    email: "mburhaan1@gmail.com",
    phone: null,
    value: 6800,
    date: "27-10-2025",
    time: "2:44 PM",
    source: "Email",
    status: "Pending",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 13,
    businessName: "Blue Jet Plumbing",
    company: null,
    contactName: null,
    email: "info@localplumbingheros.com.au",
    phone: null,
    value: 11200,
    date: "27-10-2025",
    time: "2:58 PM",
    source: "Email",
    status: "Quote",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 14,
    businessName: "Events by AA",
    company: null,
    contactName: null,
    email: "Aroosazara17@gmail.com",
    phone: null,
    value: 19500,
    date: "28-10-2025",
    time: "11:45 AM",
    source: "Email",
    status: "Quote",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 15,
    businessName: "OBM Demolition",
    company: null,
    contactName: "Ali",
    email: "info@allinit.com.au",
    phone: "0414441371",
    value: 35000,
    date: "06-11-2025",
    time: "7:46 AM",
    source: "Website",
    status: "Won",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 16,
    businessName: "Strap n Go",
    company: null,
    contactName: null,
    email: "info@strapngo.com.au",
    phone: null,
    value: 7400,
    date: "17-11-2025",
    time: "11:01 AM",
    source: "Email",
    status: "Quote",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 17,
    businessName: "Strap n Go",
    company: null,
    contactName: null,
    email: "info@strapngo.com.au",
    phone: null,
    value: 7400,
    date: "17-11-2025",
    time: "11:01 AM",
    source: "Email",
    status: "Quote",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
  {
    id: 18,
    businessName: "The Egyptian Orphan Fund Australia",
    company: null,
    contactName: "Info",
    email: "info@theegyptianorphanfund.org.au",
    phone: null,
    value: 5600,
    date: "15-12-2025",
    time: "12:11 PM",
    source: "Email",
    status: "Pending",
    trigger: null,
    file: null,
    dropboxFilePath: null,
  },
];

export interface SidebarModule {
  id: string;
  label: string;
  route: string;
  icon: "dollar" | "document" | "users" | "settings" | "home" | "phone" | "ticket" | "whatsapp";
  badge?: { count: number; color: "red" | "blue" };
  disabled?: boolean;
  comingSoon?: boolean;
}

export const SIDEBAR_MODULES: SidebarModule[] = [
  {
    id: "debt-recovery",
    label: "Debt Recovery",
    route: "/automations/debt-recovery",
    icon: "dollar",
  },
  {
    id: "quote-pipeline",
    label: "Quote Pipeline",
    route: "/automations/quote-pipeline",
    icon: "document",
  },
  {
    id: "voice-agents",
    label: "Voice Agents",
    route: "/automations/voice-agents",
    icon: "phone",
  },
  {
    id: "tickets",
    label: "IT Support",
    route: "/automations/tickets",
    icon: "ticket",
  },
  {
    id: "whatsapp-groups",
    label: "WhatsApp Broadcast",
    route: "/automations/whatsapp-groups",
    icon: "whatsapp",
  },
  {
    id: "whatsapp-participants",
    label: "WhatsApp Groups & Participants",
    route: "/automations/whatsapp-participants",
    icon: "users",
  },
];
